---
- name: Backup and Modify SSH Configuration with Timestamp
  hosts: all
  become: yes
  tasks:
    - name: Get current timestamp
      shell: "date +'%Y-%m-%d_%H-%M-%S'"
      register: current_timestamp

    - name: Create backup of sshd_config with timestamp
      copy:
        src: /etc/ssh/sshd_config
        dest: "/path/to/backup/sshd_config.bak_{{ current_timestamp.stdout }}"
        backup: yes
      notify: Print backup message

    - name: Modify sshd_config file
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#PermitRootLogin'
        line: 'PermitRootLogin no'
      notify: Print modification message

  handlers:
    - name: Print backup message
      debug:
        msg: "Backup of sshd_config created as /path/to/backup/sshd_config.bak_{{ current_timestamp.stdout }}"

    - name: Print modification message
      debug:
        msg: "sshd_config file modified. Please manually reboot the system for verification."

    - name: Prompt for manual reboot
      debug:
        msg: "Please manually reboot the system for verification after completing the playbook execution."

