---
- name: Backup and configure sshd_config
  hosts: all
  become: yes 
  tasks:
    - name: Create backup of sshd_config with timestamp
      copy:
        src: /etc/ssh/sshd_config
        dest: "/etc/ssh/sshd_config.bak_{{ ansible_date_time.iso8601_basic }}"
        remote_src: yes  # Ensures that the file is found on the remote host

    - name: Modify sshd_config to disable root login (Example change)
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#PermitRootLogin'
        line: 'PermitRootLogin no'
        backup: yes  # Create backup before making changes to sshd_config

    - name: Restart SSH service to apply changes
      service:
        name: sshd
        state: restarted
        enabled: yes
