---
- name: Ensure PASS_WARN_AGE is set to 10 days
  hosts: all
  become: true
  vars:
    pass_warn_days: 10
    login_defs: /etc/login.defs
    login_defs_backup: "/etc/login.defs.backup_{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
  tasks:

    - name: Backup /etc/login.defs with timestamp
      copy:
        src: "{{ login_defs }}"
        dest: "{{ login_defs_backup }}"
        remote_src: yes
      when: login_defs is file

    - name: Set PASS_WARN_AGE to 10 in /etc/login.defs
      lineinfile:
        path: "{{ login_defs }}"
        regexp: '^\s*PASS_WARN_AGE\s+'
        line: "PASS_WARN_AGE {{ pass_warn_days }}"
        create: yes

    - name: Get list of local users with password set
      command: >
        awk -F: '$$2 !~ /^[!*]/ { print $$1 }' /etc/shadow
      register: passwd_users
      changed_when: false

    - name: Set password warn days to 10 for users with password
      command: "chage --warndays {{ pass_warn_days }} {{ item }}"
      loop: "{{ passwd_users.stdout_lines }}"
      when: item != 'root'  # Optional: skip root if desired

    - name: Reminder to manually reboot the system
      debug:
        msg: |
          Manual reboot required to verify changes.
          Please run: reboot
