---
- name: Secure SSH configuration with backup
  hosts: all
  become: true
  vars:
    ssh_config_path: /etc/ssh/sshd_config
    timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}"
    backup_file: "{{ ssh_config_path }}.bak_{{ timestamp }}"

  tasks:

    - name: Check if sshd_config exists
      stat:
        path: "{{ ssh_config_path }}"
      register: ssh_config_stat

    - name: Backup sshd_config with timestamp
      copy:
        src: "{{ ssh_config_path }}"
        dest: "{{ backup_file }}"
        remote_src: true
      when: ssh_config_stat.stat.exists

    - name: Example - Disable root login (customize as needed)
      lineinfile:
        path: "{{ ssh_config_path }}"
        regexp: '^#?PermitRootLogin\s+.*'
        line: 'PermitRootLogin no'
        backup: no

    - name: Example - Set MaxAuthTries to 3
      lineinfile:
        path: "{{ ssh_config_path }}"
        regexp: '^#?MaxAuthTries\s+.*'
        line: 'MaxAuthTries 3'
        backup: no

    - name: Reminder to manually reboot
      debug:
        msg: |
         SH configuration has been updated and backed up as:
          {{ backup_file }}

          Please reboot the system manually to apply changes and verify SSH behavior.
