---
- name: Ensure PASS_WARN_AGE is 10 or more and update user warn days
  hosts: all
  become: yes
  vars:
    login_defs_path: /etc/login.defs
    backup_dir: /root/login_defs_backups
    pass_warn_age_value: 10
  tasks:

    - name: Create backup directory if it doesn't exist
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'

    - name: Backup /etc/login.defs with timestamp
      copy:
        src: "{{ login_defs_path }}"
        dest: "{{ backup_dir }}/login.defs.backup_{{ ansible_date_time.iso8601 }}"
        remote_src: yes
        mode: preserve

    - name: Ensure PASS_WARN_AGE is set to 10 or more
      lineinfile:
        path: "{{ login_defs_path }}"
        regexp: '^(#\s*)?PASS_WARN_AGE\s+'
        line: "PASS_WARN_AGE {{ pass_warn_age_value }}"
        state: present
        backrefs: yes

    - name: Get list of users with password set
      command: awk -F: '$2 !~ /^[!*]/ {print $1}' /etc/shadow
      register: users_with_password
      changed_when: false

    - name: Set password warn days for all users with a password
      command: chage --warndays {{ pass_warn_age_value }} {{ item }}
      loop: "{{ users_with_password.stdout_lines }}"
      when: item not in ['nfsnobody', 'nobody']  # Skip system accounts if needed
      ignore_errors: yes  # If some users can't be changed (like system accounts), skip
