---
- name: Ensure AIDE is installed and initialized
  hosts: all
  become: yes
  tasks:
    - name: Install AIDE
      yum:
        name: aide
        state: present

    - name: Backup existing AIDE database (if exists)
      command: cp /var/lib/aide/aide.db.gz /var/lib/aide/aide.db.gz-$(date +%Y%m%d-%H%M%S)
      args:
        removes: /var/lib/aide/aide.db.gz
      ignore_errors: yes  # Prevent failure if the file doesn't exist

    - name: Initialize AIDE database
      command: aide --init
      args:
        creates: /var/lib/aide/aide.db.new.gz

    - name: Move AIDE database
      command: mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz
      args:
        removes: /var/lib/aide/aide.db.new.gz

    - name: Create final backup with timestamp after initialization
      command: cp /var/lib/aide/aide.db.gz /var/lib/aide/aide.db.gz-$(date +%Y%m%d-%H%M%S)
