---
- name: Ensure ASLR is enabled with proper backup and best practices
  hosts: all
  become: true
  vars:
    sysctl_file: /etc/sysctl.d/60-kernel_sysctl.conf

  tasks:

    - name: Create backup of sysctl file with timestamp
      shell: |
        set -e
        TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)
        cp {{ sysctl_file }} {{ sysctl_file }}.bak_$TIMESTAMP
      args:
        executable: /bin/bash
      ignore_errors: yes  # In case the file doesn't exist yet

    - name: Ensure kernel.randomize_va_space is set in sysctl config
      lineinfile:
        path: "{{ sysctl_file }}"
        regexp: '^kernel.randomize_va_space'
        line: 'kernel.randomize_va_space = 2'
        create: yes
        state: present

    - name: Apply the sysctl setting immediately
      sysctl:
        name: kernel.randomize_va_space
        value: '2'
        state: present
        reload: yes

    - name: Confirm current kernel value of randomize_va_space
      command: sysctl kernel.randomize_va_space
      register: aslr_status

    - name: Show current ASLR status
      debug:
        msg: "{{ aslr_status.stdout }}"

    - name: Notify manual reboot
      debug:
        msg: |
           ASLR configuration updated successfully.
           Please manually reboot the system to fully apply all kernel-level changes.
         

