---
- name: Ensure only authorized groups are assigned ownership of audit log files (CIS 5.2.4.4)
  hosts: all
  become: true
  vars:
    audit_conf_file: /etc/audit/auditd.conf
    log_group: adm
    timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}"

  tasks:

    - name: Backup auditd.conf with timestamp
      copy:
        src: "{{ audit_conf_file }}"
        dest: "{{ audit_conf_file }}.bak_{{ timestamp }}"
        remote_src: yes

    - name: Set log_group to adm in auditd.conf
      lineinfile:
        path: "{{ audit_conf_file }}"
        regexp: '^(\s*)log_group\s*='
        line: 'log_group = {{ log_group }}'
        state: present
        backrefs: yes
        create: no

    - name: Get log file directory from auditd.conf
      shell: |
        awk -F '=' '/^\s*log_file\s*=/ {print $2}' "{{ audit_conf_file }}" | xargs dirname
      register: audit_log_dir
      changed_when: false

    - name: Change group ownership of audit log files to adm (or root)
      shell: |
        find {{ audit_log_dir.stdout }} -type f ! -group adm ! -group root -exec chgrp adm {} +
      args:
        warn: false

    - name: Change group of /var/log/audit to adm
      file:
        path: /var/log/audit
        group: adm
        recurse: yes
        state: directory

    - name: Restart auditd to apply changes
      systemd:
        name: auditd
        state: restarted
        enabled: yes
      register: result
      until: result is succeeded
      retries: 3
      delay: 5

    - name: Reminder to manually reboot system for verification
      debug:
        msg: "Manual reboot recommended to verify auditd settings. Backup saved as {{ audit_conf_file }}.bak_{{ timestamp }}"
