- name: Fix auditd log_group and permissions
  hosts: all
  become: yes

  tasks:
    # Backup configuration file with timestamp
    - name: Backup auditd.conf with timestamp
      copy:
        src: /etc/audit/auditd.conf
        dest: "/etc/audit/auditd.conf.bak_{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}"
        remote_src: yes

    # Ensure the adm group exists
    - name: Ensure 'adm' group exists
      group:
        name: adm
        state: present

    # Modify log_group setting in auditd.conf
    - name: Set correct 'log_group = adm' in auditd.conf
      replace:
        path: /etc/audit/auditd.conf
        regexp: '^(#?\s*log_group\s*=\s*).*'
        replace: 'log_group = adm'

    # Ensure /var/log/audit directory exists
    - name: Ensure /var/log/audit exists
      file:
        path: /var/log/audit
        state: directory
        owner: root
        group: adm
        mode: '0750'

    # Set file group ownership for audit logs
    - name: Ensure audit log files are owned by adm group
      shell: |
        find /var/log/audit/ -type f ! -group adm ! -group root -exec chgrp adm {} +
      args:
        executable: /bin/bash

    # Restart the auditd service and handle potential failure
    - name: Restart auditd to apply changes
      systemd:
        name: auditd
        state: restarted
        enabled: yes
      register: result
      failed_when: result.rc != 0
      retries: 3
      delay: 5
      until: result.rc == 0

  handlers:
    - name: Manual Reboot Reminder
      debug:
        msg: "Please manually reboot the system to complete the verification."
