---
- name: Ensure audit and backlog limit is set in GRUB2
  hosts: all
  become: yes
  tasks:

    - name: Gather current GRUB_CMDLINE_LINUX
      command: grubby --info=ALL
      register: grubby_info

    - name: Backup current GRUB2 config
      copy:
        src: /boot/grub2/grub.cfg
        dest: /boot/grub2/grub.cfg.bak
        remote_src: yes
      when: ansible_facts['os_family'] == "RedHat"

    - name: Ensure audit=1 is present in kernel args
      command: grubby --update-kernel=ALL --args="audit=1"
      register: audit_flag

    - name: Ensure audit_backlog_limit=8192 is present
      command: grubby --update-kernel=ALL --args="audit_backlog_limit=8192"
      register: backlog_flag

    - name: Ensure grubenv file exists (required for grub2-editenv)
      file:
        path: /boot/grub2/grubenv
        state: touch
        mode: '0644'

    - name: Regenerate GRUB2 configuration
      command: grub2-mkconfig -o /boot/grub2/grub.cfg
      register: grub_config_result
      failed_when: grub_config_result.rc != 0 and
                   "'cannot rename the file' not in grub_config_result.stderr"

    - name: Display manual reboot reminder
      debug:
        msg: |
          Kernel parameters updated. A reboot is required to apply changes.
          Please reboot the system manually at your convenience.

