---
- name: Fix auditd log_group and permissions
  hosts: all
  become: yes

  tasks:

    - name: Backup auditd.conf with timestamp
      copy:
        src: /etc/audit/auditd.conf
        dest: "/etc/audit/auditd.conf.bak_{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}"
        remote_src: yes

    - name: Ensure 'adm' group exists
      group:
        name: adm
        state: present

    - name: Set correct 'log_group = adm' in auditd.conf
      replace:
        path: /etc/audit/auditd.conf
        regexp: '^(#?\s*log_group\s*=\s*).*'
        replace: 'log_group = adm'

    - name: Ensure /var/log/audit exists
      file:
        path: /var/log/audit
        state: directory
        owner: root
        group: adm
        mode: '0750'

    - name: Ensure audit log files are owned by adm group
      shell: |
        find /var/log/audit/ -type f ! -group adm ! -group root -exec chgrp adm {} +
      args:
        executable: /bin/bash

    - name: Restart auditd to apply changes
      systemd:
        name: auditd
        state: restarted
        enabled: yes

  handlers:
    - name: Manual Reboot Reminder
      debug:
        msg: "Please manually reboot the system to complete the verification."
