---
- name: Ensure auditing is enabled and backlog limit is sufficient
  hosts: all
  become: yes
  vars:
    grub_file_bios: /boot/grub2/grub.cfg
    grub_file_uefi: /boot/efi/EFI/redhat/grub.cfg
    grubenv_file: /boot/grub2/grubenv
    audit_args: "audit=1 audit_backlog_limit=8192"

  tasks:

    - name: Check if BIOS GRUB config exists
      stat:
        path: "{{ grub_file_bios }}"
      register: grub_bios

    - name: Check if UEFI GRUB config exists
      stat:
        path: "{{ grub_file_uefi }}"
      register: grub_uefi

    - name: Set GRUB config path dynamically
      set_fact:
        grub_cfg_path: "{{ grub_file_bios if grub_bios.stat.exists else grub_file_uefi }}"

    - name: Backup current GRUB config (manual restore if needed)
      copy:
        src: "{{ grub_cfg_path }}"
        dest: "{{ grub_cfg_path }}.bak"
        remote_src: yes
      when: grub_bios.stat.exists or grub_uefi.stat.exists

    - name: Ensure GRUB_CMDLINE_LINUX contains audit args
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX="(.*)"'
        line: 'GRUB_CMDLINE_LINUX="\1 {{ audit_args }}"'
        backrefs: yes

    - name: Update GRUB with audit parameters
      command: grubby --update-kernel=ALL --args="{{ audit_args }}"

    - name: Rebuild GRUB config file (for BIOS systems)
      command: grub2-mkconfig -o "{{ grub_file_bios }}"
      when: grub_bios.stat.exists

    - name: Rebuild GRUB config file (for UEFI systems)
      command: grub2-mkconfig -o "{{ grub_file_uefi }}"
      when: grub_uefi.stat.exists

    - name: Reminder to reboot manually
      debug:
        msg: "Manual reboot required for GRUB changes to take effect. Please reboot the system."
