---
- name: Ensure /etc/motd has the correct banner with hostname
  hosts: all
  become: true
  vars:
    motd_file: /etc/motd

  tasks:
    - name: Get system hostname
      ansible.builtin.hostname:
      register: hostname_info

    - name: Create expected banner content
      set_fact:
        expected_banner: |
          **********************************************************************************
          *                                                                                *
          * Welcome to {{ hostname_info.name }}{{ ' ' * (67 - hostname_info.name | length) }}*
          *                                                                                *
          *                                                                                *
          **********************************************************************************

    - name: Check if /etc/motd exists
      ansible.builtin.stat:
        path: "{{ motd_file }}"
      register: motd_stat

    - name: Read current /etc/motd content
      ansible.builtin.slurp:
        path: "{{ motd_file }}"
      when: motd_stat.stat.exists
      register: motd_content

    - name: Decode existing MOTD content
      set_fact:
        current_motd: "{{ motd_content.content | b64decode }}"
      when: motd_stat.stat.exists

    - name: Backup existing MOTD if different
      ansible.builtin.copy:
        src: "{{ motd_file }}"
        dest: "{{ motd_file }}.bak.{{ ansible_date_time.iso8601 | regex_replace('[^0-9]', '') }}"
        remote_src: true
      when: motd_stat.stat.exists and current_motd != expected_banner

    - name: Update MOTD if different or create if not exists
      ansible.builtin.copy:
        content: "{{ expected_banner }}"
        dest: "{{ motd_file }}"
        owner: root
        group: root
        mode: '0644'
      when: not motd_stat.stat.exists or current_motd != expected_banner
