---
- name: CIS 2.1.2 - Ensure chrony is configured with input IP
  hosts: all
  become: yes
  vars:
    chrony_conf: /etc/chrony.conf
    chrony_d_dir: /etc/chrony.d
    ntp_server_ip: "{{ input_ntp_server_ip | default('pool.ntp.org') }}"

  tasks:
    - name: Install chrony package
      package:
        name: chrony
        state: present

    - name: Ensure chronyd service is enabled and started
      service:
        name: chronyd
        state: started
        enabled: true

    - name: Backup chrony.conf
      copy:
        src: "{{ chrony_conf }}"
        dest: "{{ chrony_conf }}.bak_{{ ansible_date_time.iso8601 }}"
        remote_src: yes
      when: chrony_conf is file

    - name: Backup chrony.d directory
      command: cp -r {{ chrony_d_dir }} {{ chrony_d_dir }}.bak_{{ ansible_date_time.iso8601 }}
      when: chrony_d_dir is directory

    - name: Ensure server line is present in /etc/chrony.conf
      lineinfile:
        path: "{{ chrony_conf }}"
        regexp: '^\s*server\s+{{ ntp_server_ip }}\s+iburst'
        line: "server {{ ntp_server_ip }} iburst"
        create: yes
        backup: yes

    - name: Restart chronyd to apply configuration
      service:
        name: chronyd
        state: restarted
