---
- name: Ensure core dump backtraces are disabled
  hosts: all
  become: yes
  tasks:
    - name: Ensure backup directory exists
      file:
        path: /etc/systemd/coredump.conf.d
        state: directory
        mode: '0755'

    - name: Backup existing coredump conf if present
      shell: |
        set -e
        FILE="/etc/systemd/coredump.conf.d/custom.conf"
        if [ -f "$FILE" ]; then
          timestamp=$(date +%F_%T)
          cp "$FILE" "${FILE}.bak_$timestamp"
        fi
      args:
        executable: /bin/bash
      register: backup_result
      changed_when: backup_result.rc == 0
      ignore_errors: true

    - name: Configure ProcessSizeMax to 0
      copy:
        dest: /etc/systemd/coredump.conf.d/custom.conf
        content: |
          [Coredump]
          ProcessSizeMax=0
        owner: root
        group: root
        mode: '0644'

    - name: Check current ProcessSizeMax setting
      command: grep -i ProcessSizeMax /etc/systemd/coredump.conf.d/custom.conf
      register: current_setting
      changed_when: false

    - name: Show current ProcessSizeMax value
      debug:
        msg: "Current ProcessSizeMax value: {{ current_setting.stdout }}"

    - name: Reminder to reboot system for changes to take effect
      debug:
        msg: "Please reboot the system manually to apply core dump configuration changes."

