---
- name: Disable cramfs kernel module securely
  hosts: all
  become: yes
  vars:
    module_name: cramfs
    timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}"
    modprobe_conf: "/etc/modprobe.d/{{ module_name }}.conf"
    backup_path: "{{ modprobe_conf }}.bak_{{ timestamp }}"

  tasks:

    - name: Check if cramfs.conf exists
      stat:
        path: "{{ modprobe_conf }}"
      register: modprobe_conf_stat

    - name: Backup cramfs.conf with timestamp if it exists
      copy:
        src: "{{ modprobe_conf }}"
        dest: "{{ backup_path }}"
        remote_src: yes
      when: modprobe_conf_stat.stat.exists
      ignore_errors: yes

    - name: Ensure cramfs is blacklisted
      lineinfile:
        path: "{{ modprobe_conf }}"
        line: "blacklist {{ module_name }}"
        create: yes
        state: present

    - name: Ensure cramfs is not loadable
      lineinfile:
        path: "{{ modprobe_conf }}"
        line: "install {{ module_name }} /bin/false"
        insertafter: EOF
        create: yes
        state: present

    - name: Unload cramfs if currently loaded
      shell: |
        if lsmod | grep -q {{ module_name }}; then
          modprobe -r {{ module_name }}
        fi
      args:
        executable: /bin/bash

    - name: Notify for manual reboot
      debug:
        msg: |
          {{ module_name | upper }} module has been disabled.
          A reboot is required to apply changes. Please reboot the system manually.
