---
- name: Disable SSH CBC Ciphers via Crypto Policy (Manual Reboot)
  hosts: all
  become: yes
  vars:
    pmod_file: /etc/crypto-policies/policies/modules/NO-SSHCBC.pmod

  tasks:

    - name: Ensure the crypto policies module directory exists
      file:
        path: /etc/crypto-policies/policies/modules
        state: directory
        mode: '0755'

    - name: Create or overwrite NO-SSHCBC.pmod file to disable CBC ciphers
      copy:
        dest: "{{ pmod_file }}"
        content: |
          # This is a subpolicy to disable all CBC mode ciphers
          # for the SSH protocol (libssh and OpenSSH)
          cipher@SSH = -*-CBC
        mode: '0644'
        backup: yes

    - name: Create a timestamped backup of the NO-SSHCBC.pmod file
      copy:
        src: "{{ pmod_file }}"
        dest: "{{ pmod_file }}.{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}.bak"
        remote_src: yes

    - name: Apply the crypto policy with NO-SSHCBC
      command: update-crypto-policies --set DEFAULT:NO-SSHCBC
      register: crypto_policy_update
      changed_when: "'Setting system-wide crypto policy' in crypto_policy_update.stdout"

    - name: Reminder to manually reboot
      debug:
        msg: |
          Crypto policy updated successfully.
          Please manually reboot the system to apply the changes:
      
