---
- name: Ensure system-wide crypto policy disables SHA1 hash and signature support and SSH CBC ciphers
  hosts: all
  become: yes
  vars:
    sha1_policy_module_path: /etc/crypto-policies/policies/modules/NO-SHA1.pmod
    sha1_policy_content: |
      # This is a subpolicy dropping the SHA1 hash and signature support
      hash = -SHA1
      sign = -*-SHA1
      sha1_in_certs = 0
    crypto_policy_sha1: "DEFAULT:NO-SHA1"

    pmod_file: /etc/crypto-policies/policies/modules/NO-SSHCBC.pmod
    crypto_policy_sshcbc: "DEFAULT:NO-SSHCBC"

  tasks:

    - name: Backup existing SHA1 policy module (if exists)
      copy:
        src: "{{ sha1_policy_module_path }}"
        dest: "{{ sha1_policy_module_path }}.bak_{{ ansible_date_time.iso8601 }}"
        remote_src: yes
      when: ansible_facts['os_family'] == 'RedHat' and
            ansible_facts['distribution_major_version']|int >= 8 and
            ansible_facts['distribution'] != "Fedora"
      ignore_errors: yes

    - name: Ensure NO-SHA1.pmod file is created with correct contents
      copy:
        dest: "{{ sha1_policy_module_path }}"
        content: "{{ sha1_policy_content }}"
        owner: root
        group: root
        mode: '0644'

    - name: Ensure the crypto policies module directory exists
      file:
        path: /etc/crypto-policies/policies/modules
        state: directory
        mode: '0755'

    - name: Create or overwrite NO-SSHCBC.pmod file to disable CBC ciphers
      copy:
        dest: "{{ pmod_file }}"
        content: |
          # This is a subpolicy to disable all CBC mode ciphers
          # for the SSH protocol (libssh and OpenSSH)
          cipher@SSH = -*-CBC
        mode: '0644'
        backup: yes

    - name: Create a timestamped backup of the NO-SSHCBC.pmod file
      copy:
        src: "{{ pmod_file }}"
        dest: "{{ pmod_file }}.{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}.bak"
        remote_src: yes

    - name: Apply the crypto policy with NO-SHA1
      command: update-crypto-policies --set {{ crypto_policy_sha1 }}
      register: crypto_policy_set
      changed_when: "'Setting system policy to' in crypto_policy_set.stdout"

    - name: Apply the crypto policy with NO-SSHCBC
      command: update-crypto-policies --set {{ crypto_policy_sshcbc }}
      register: crypto_policy_update
      changed_when: "'Setting system-wide crypto policy' in crypto_policy_update.stdout"

    - name: Notify user to manually reboot the system
      debug:
        msg: |
          Crypto policy has been updated to "{{ crypto_policy_sha1 }}" and "{{ crypto_policy_sshcbc }}".
          Manual reboot is required to apply changes. 
          Please reboot the system at your convenience.

