---
- name: Ensure auditing for processes that start prior to auditd is enabled
  hosts: all
  become: yes
  tasks:
    - name: Backup current GRUB2 configuration
      copy:
        src: /etc/default/grub
        dest: "/etc/default/grub.bak_{{ ansible_date_time.iso8601_basic }}"
        remote_src: yes

    - name: Backup current GRUB2 config file
      copy:
        src: /boot/grub2/grub.cfg
        dest: "/boot/grub2/grub.cfg.bak_{{ ansible_date_time.iso8601_basic }}"
        remote_src: yes

    - name: Add audit=1 to GRUB2 kernel args
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX="'
        line: 'GRUB_CMDLINE_LINUX="audit=1"'
        backup: yes
      notify:
        - Rebuild GRUB2 config

    - name: Rebuild GRUB2 config
      command: grub2-mkconfig -o /boot/grub2/grub.cfg

    - name: Pause and wait for manual reboot
      pause:
        prompt: "The system needs to be rebooted to apply the changes. Please reboot manually and press Enter to continue."

    - name: Verify audit=1 is applied
      shell: grubby --info=ALL | grep -Po '\baudit=1\b'
      register: audit_check
      failed_when: audit_check.stdout == ''
      changed_when: false
      ignore_errors: true

    - name: Fail if audit=1 is not present
      fail:
        msg: "Audit parameter not found in GRUB2 configuration."
      when: audit_check.stdout == ''

