---
- name: Remediate CIS 4.4.3.2.7 - Enforce password quality for root
  hosts: all
  become: yes
  vars:
    pwquality_root_conf: /etc/security/pwquality.conf.d/50-pwroot.conf
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"

  tasks:

    - name: Ensure pwquality configuration directory exists
      file:
        path: /etc/security/pwquality.conf.d
        state: directory
        mode: '0755'

    - name: Backup existing pwroot.conf if it exists
      copy:
        src: "{{ pwquality_root_conf }}"
        dest: "{{ pwquality_root_conf }}.{{ timestamp }}"
        remote_src: yes
      when: lookup('ansible.builtin.file', pwquality_root_conf, errors='ignore')

    - name: Ensure 'enforce_for_root' is set in pwquality root conf
      lineinfile:
        path: "{{ pwquality_root_conf }}"
        regexp: '^\s*enforce_for_root\b'
        line: 'enforce_for_root'
        create: yes
        mode: '0644'

    - name: Manual reboot reminder
      debug:
        msg: "✔Please manually reboot the system to complete verification for CIS 4.4.3.2.7."
