---
- name: Ensure password failed attempts lockout is configured (deny = 3)
  hosts: all
  become: yes
  vars:
    faillock_conf: "/etc/security/faillock.conf"
    timestamp: "{{ lookup('pipe', 'date +%F_%H-%M-%S') }}"
    backup_file: "{{ faillock_conf }}.bak_{{ timestamp }}"

  tasks:
    - name: Backup faillock.conf with timestamp
      copy:
        src: "{{ faillock_conf }}"
        dest: "{{ backup_file }}"
        remote_src: yes
        mode: '0644'

    - name: Ensure 'deny = 3' is present in faillock.conf
      lineinfile:
        path: "{{ faillock_conf }}"
        regexp: '^\s*deny\s*='
        line: 'deny = 3'
        state: present
        create: yes
        backup: no
      notify:
        - Show result

  handlers:
    - name: Show result
      debug:
        msg: "'deny = 3' ensured in {{ faillock_conf }}"
