---
- name: Secure rsyslog configuration as per CIS benchmarks
  hosts: localhost
  become: true
  vars:
    rsyslog_conf_path: /etc/rsyslog.conf
    rsyslog_conf_backup: "/etc/rsyslog.conf.{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"

  tasks:

    - name: Ensure rsyslog is installed
      package:
        name: rsyslog
        state: present

    - name: Backup current rsyslog.conf
      copy:
        src: "{{ rsyslog_conf_path }}"
        dest: "{{ rsyslog_conf_backup }}"
        remote_src: yes

    - name: Harden rsyslog config - enable high precision timestamps
      lineinfile:
        path: "{{ rsyslog_conf_path }}"
        regexp: '^\\$ActionFileDefaultTemplate'
        line: '$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat'
        create: yes
        state: present

    - name: Ensure log files are written synchronously
      lineinfile:
        path: "{{ rsyslog_conf_path }}"
        regexp: '^\\$ActionFileEnableSync'
        line: '$ActionFileEnableSync on'
        create: yes
        state: present

    - name: Ensure rsyslog does not accept remote messages unless needed
      lineinfile:
        path: "{{ rsyslog_conf_path }}"
        regexp: '^(\\$ModLoad imudp|\\$UDPServerRun|\\$ModLoad imtcp|\\$InputTCPServerRun)'
        state: absent

    - name: Unmask rsyslog service (if masked)
      command: systemctl unmask rsyslog
      ignore_errors: true

    - name: Enable rsyslog service
      systemd:
        name: rsyslog
        enabled: true

    - name: Restart rsyslog to apply new configuration
      systemd:
        name: rsyslog
        state: restarted
        daemon_reload: yes
