---
- name: Configure GNOME screensaver lock settings
  hosts: all
  become: true
  vars:
    timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}"
    dconf_config_file: /etc/dconf/db/local.d/00-screensaver
    dconf_lock_file: /etc/dconf/db/local.d/locks/00-screensaver

  tasks:

    - name: Backup existing dconf config file if it exists
      copy:
        src: "{{ dconf_config_file }}"
        dest: "{{ dconf_config_file }}.bak_{{ timestamp }}"
        remote_src: true
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] | int >= 7
      ignore_errors: true

    - name: Create or overwrite dconf config file for screensaver settings
      copy:
        dest: "{{ dconf_config_file }}"
        content: |
          [org/gnome/desktop/session]
          idle-delay=uint32 300

          [org/gnome/desktop/screensaver]
          lock-delay=uint32 5
        mode: '0644'

    - name: Create or update dconf lock file
      blockinfile:
        path: "{{ dconf_lock_file }}"
        create: true
        block: |
          /org/gnome/desktop/session/idle-delay
          /org/gnome/desktop/screensaver/lock-delay
        mode: '0644'

    - name: Apply dconf settings
      command: dconf update

    - name: Reminder for manual reboot
      debug:
        msg: "Please reboot the system manually to apply changes. (Manual Reboot Required)"
