---
- name: System Hardening Playbook
  hosts: all
  become: true
  vars:
    timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}"

  tasks:

    - name: Ensure sshd_config exists before backing up
      stat:
        path: /etc/ssh/sshd_config
      register: sshd_config_stat

    - name: Backup sshd_config with timestamp
      copy:
        src: /etc/ssh/sshd_config
        dest: "/etc/ssh/sshd_config.bak_{{ timestamp }}"
        remote_src: yes
      when: sshd_config_stat.stat.exists

    - name: Check if GDM is installed (RPM-based or Debian-based)
      shell: |
        if command -v rpm &> /dev/null; then
          rpm -q gdm
        elif command -v dpkg-query &> /dev/null; then
          dpkg-query -W gdm
        else
          exit 1
        fi
      register: gdm_check
      failed_when: false
      changed_when: false

    - name: Set fact if GDM is installed
      set_fact:
        gdm_installed: "{{ 'is not installed' not in gdm_check.stdout and gdm_check.rc == 0 }}"

    - name: Debug GDM installed status
      debug:
        msg: "GDM installed: {{ gdm_installed }}"

    - name: Fail if GDM is not installed
      fail:
        msg: "GDM is not installed. This task is not applicable."
      when: not gdm_installed

    - name: Lock GNOME automount settings if GDM is installed
      block:
        - name: Create lock file for automount
          copy:
            content: |
              /org/gnome/desktop/media-handling/automount
              /org/gnome/desktop/media-handling/automount-open
            dest: /etc/dconf/db/local.d/locks/00-media-automount

        - name: Update dconf database
          command: dconf update
      when: gdm_installed

    - name: Notify user to manually reboot
      debug:
        msg: "Script complete. Please **manually reboot** the system to apply changes."
