---
- name: Disable screensaver and screen lock for GNOME
  hosts: all
  become: true
  vars:
    dconf_dir: /etc/dconf/db
    dconf_profile: local
    screensaver_file: 00-screensaver
    timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}"

  tasks:
    - name: Ensure dconf directories exist
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ dconf_dir }}/{{ dconf_profile }}.d"
        - "{{ dconf_dir }}/{{ dconf_profile }}.d/locks"

    - name: Stat the screensaver config file
      stat:
        path: "{{ dconf_dir }}/{{ dconf_profile }}.d/{{ screensaver_file }}"
      register: screensaver_file_stat

    - name: Backup existing screensaver config if present
      copy:
        src: "{{ dconf_dir }}/{{ dconf_profile }}.d/{{ screensaver_file }}"
        dest: "{{ dconf_dir }}/{{ dconf_profile }}.d/{{ screensaver_file }}.bak_{{ timestamp }}"
        remote_src: yes
      when: screensaver_file_stat.stat.exists

    - name: Disable screensaver and screen lock settings
      copy:
        dest: "{{ dconf_dir }}/{{ dconf_profile }}.d/{{ screensaver_file }}"
        content: |
          [org/gnome/desktop/session]
          idle-delay=uint32 0

          [org/gnome/desktop/screensaver]
          lock-enabled=false
          idle-activation-enabled=false

    - name: Stat the screensaver lock file
      stat:
        path: "{{ dconf_dir }}/{{ dconf_profile }}.d/locks/{{ screensaver_file }}"
      register: screensaver_lock_stat

    - name: Backup existing lock file if present
      copy:
        src: "{{ dconf_dir }}/{{ dconf_profile }}.d/locks/{{ screensaver_file }}"
        dest: "{{ dconf_dir }}/{{ dconf_profile }}.d/locks/{{ screensaver_file }}.bak_{{ timestamp }}"
        remote_src: yes
      when: screensaver_lock_stat.stat.exists

    - name: Lock down the settings
      copy:
        dest: "{{ dconf_dir }}/{{ dconf_profile }}.d/locks/{{ screensaver_file }}"
        content: |
          /org/gnome/desktop/session/idle-delay
          /org/gnome/desktop/screensaver/lock-enabled
          /org/gnome/desktop/screensaver/idle-activation-enabled

    - name: Update dconf database
      command: dconf update

    - name: Reminder - Manual Reboot Required
      debug:
        msg: |
          Screensaver and lock settings have been hardened.
          Please reboot the system manually to apply changes.
