---
- name: Configure GNOME screensaver settings
  hosts: all
  become: true
  vars:
    timestamp: "{{ lookup('pipe', 'date +%F_%H-%M-%S') }}"
    gsettings_files_dir: "/etc/dconf/db/local.d"
    gsettings_locks_dir: "/etc/dconf/db/local.d/locks"

  tasks:

    - name: Find files with idle-delay setting
      find:
        paths: "{{ gsettings_files_dir }}"
        patterns: '*'
        contains: 'idle-delay'
        file_type: file
      register: idle_delay_files

    - name: Find files with lock-delay setting
      find:
        paths: "{{ gsettings_files_dir }}"
        patterns: '*'
        contains: 'lock-delay'
        file_type: file
      register: lock_delay_files

    - name: Backup and lock idle-delay
      block:
        - name: Backup idle-delay file
          copy:
            src: "{{ item.path }}"
            dest: "{{ item.path }}.bak_{{ timestamp }}"
          loop: "{{ idle_delay_files.files }}"
          loop_control:
            label: "{{ item.path }}"

        - name: Create locks directory if needed (idle-delay)
          file:
            path: "{{ item.path | dirname }}/locks"
            state: directory
          loop: "{{ idle_delay_files.files }}"
          loop_control:
            label: "{{ item.path }}"

        - name: Write lock file for idle-delay
          copy:
            dest: "{{ item.path | dirname }}/locks/00-screensaver"
            content: "/org/gnome/desktop/session/idle-delay\n"
          loop: "{{ idle_delay_files.files }}"
          loop_control:
            label: "{{ item.path }}"
      when: idle_delay_files.files is defined and idle_delay_files.files | length > 0

    - name: Backup and lock lock-delay
      block:
        - name: Backup lock-delay file
          copy:
            src: "{{ item.path }}"
            dest: "{{ item.path }}.bak_{{ timestamp }}"
          loop: "{{ lock_delay_files.files }}"
          loop_control:
            label: "{{ item.path }}"

        - name: Create locks directory if needed (lock-delay)
          file:
            path: "{{ item.path | dirname }}/locks"
            state: directory
          loop: "{{ lock_delay_files.files }}"
          loop_control:
            label: "{{ item.path }}"

        - name: Write lock file for lock-delay
          copy:
            dest: "{{ item.path | dirname }}/locks/00-screensaver"
            content: "/org/gnome/desktop/screensaver/lock-delay\n"
          loop: "{{ lock_delay_files.files }}"
          loop_control:
            label: "{{ item.path }}"
      when: lock_delay_files.files is defined and lock_delay_files.files | length > 0

    - name: Notify about reboot
      debug:
        msg: |
          All settings and locks are applied. Please reboot the system manually to apply changes.
          Example backup files created: /etc/dconf/db/local.d/00-screensaver.bak_{{ timestamp }}
