---
- name: Secure GDM Automount and SSH Config
  hosts: all
  become: true
  vars:
    timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}"
    sshd_config_path: /etc/ssh/sshd_config
    sshd_backup_path: "/etc/ssh/sshd_config.bak_{{ timestamp }}"

  tasks:

    - name: Check if GDM is installed
      command: which gdm
      register: gdm_check
      ignore_errors: true

    - name: Set gdm_installed variable
      set_fact:
        gdm_installed: "{{ gdm_check.rc == 0 }}"

    - name: Skip GDM tasks if not installed
      debug:
        msg: "GDM is not installed. Skipping GNOME automount lock tasks."
      when: not gdm_installed

    - name: Lock GNOME automount settings if GDM is installed
      block:
        - name: Ensure dconf lock directory exists
          file:
            path: /etc/dconf/db/local.d/locks
            state: directory
            mode: '0755'

        - name: Create lock file for automount
          copy:
            content: |
              /org/gnome/desktop/media-handling/automount
              /org/gnome/desktop/media-handling/automount-open
            dest: /etc/dconf/db/local.d/locks/00-media-automount

        - name: Update dconf database
          command: dconf update
      when: gdm_installed

    - name: Backup sshd_config with timestamp
      copy:
        src: "{{ sshd_config_path }}"
        dest: "{{ sshd_backup_path }}"
        remote_src: yes

    - name: Display reboot reminder
      debug:
        msg: "Please reboot the system manually to apply all changes."
