---
- name: Lock GDM screen settings and create backups
  hosts: localhost
  become: yes
  vars:
    timestamp: "{{ lookup('pipe', 'date +%F_%H-%M-%S') }}"

  tasks:

    - name: Ensure dconf settings directory exists
      file:
        path: "/etc/dconf/db/local.d"
        state: directory
        mode: '0755'

    - name: Ensure dconf locks directory exists
      file:
        path: "/etc/dconf/db/local.d/locks"
        state: directory
        mode: '0755'

    - name: Backup existing 00-screensaver config if it exists
      copy:
        src: /etc/dconf/db/local.d/00-screensaver
        dest: "/etc/dconf/db/local.d/00-screensaver.bak_{{ timestamp }}"
        remote_src: yes
      when: ansible_facts['distribution'] != 'Unknown' and
            ansible_facts['os_family'] != 'Windows' and
            ansible_facts['distribution'] != 'MacOSX' and
            ansible_facts['distribution'] != 'Darwin'
      ignore_errors: true

    - name: Backup existing 00-screensaver lock if it exists
      copy:
        src: /etc/dconf/db/local.d/locks/00-screensaver
        dest: "/etc/dconf/db/local.d/locks/00-screensaver.bak_{{ timestamp }}"
        remote_src: yes
      ignore_errors: true

    - name: Set idle-delay and lock-delay settings
      copy:
        dest: /etc/dconf/db/local.d/00-screensaver
        content: |
          [org/gnome/desktop/session]
          idle-delay=uint32 300

          [org/gnome/desktop/screensaver]
          lock-delay=uint32 5
          lock-enabled=true
        mode: '0644'

    - name: Lock idle-delay and lock-delay keys
      copy:
        dest: /etc/dconf/db/local.d/locks/00-screensaver
        content: |
          /org/gnome/desktop/session/idle-delay
          /org/gnome/desktop/screensaver/lock-delay
        mode: '0644'

    - name: Update dconf database
      command: dconf update

    - name: Reminder to manually reboot system
      debug:
        msg: |
          Reboot is required for settings to take effect.
          Please reboot the system manually. 
