---
- name: Ensure GRUB Bootloader Password is Set
  hosts: all
  become: yes
  vars:
    timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}"  # Define the timestamp here
    grub_password: "{{ lookup('pipe', 'echo -n \"my_secure_password\" | grub2-setpassword') }}"

  tasks:
    - name: Set GRUB bootloader password
      command: grub2-setpassword
      args:
        creates: /etc/grub.d/40_custom
      register: grub_set_password
      ignore_errors: yes

    - name: Verify GRUB password is set
      command: "grep -q 'GRUB2_PASSWORD' /etc/default/grub"
      register: grub_password_check
      changed_when: false
      failed_when: grub_password_check.rc != 0

    - name: Backup /etc/default/grub before any changes
      copy:
        src: /etc/default/grub
        dest: "/etc/default/grub.bak_{{ timestamp }}"  # Ensure timestamp is quoted
        remote_src: yes
      when: grub_password_check.rc == 0

    - name: Ensure grub.cfg is updated with new password setting
      command: grub2-mkconfig -o /boot/grub2/grub.cfg
      when: grub_password_check.rc == 0

  handlers:
    - name: Restart GRUB to apply changes
      command: grub2-reboot
      when: grub_password_check.rc == 0
