---
- name: Ensure password history is configured
  hosts: all
  become: yes
  tasks:

    - name: Backup system-auth with timestamp
      command: cp /etc/pam.d/system-auth /etc/pam.d/system-auth.bak_{{ ansible_date_time.iso8601 }}
      register: system_auth_backup

    - name: Backup password-auth with timestamp
      command: cp /etc/pam.d/password-auth /etc/pam.d/password-auth.bak_{{ ansible_date_time.iso8601 }}
      register: password_auth_backup

    - name: Backup pwhistory.conf with timestamp
      command: cp /etc/security/pwhistory.conf /etc/security/pwhistory.conf.bak_{{ ansible_date_time.iso8601 }}
      register: pwhistory_backup

    - name: Set remember=24 in /etc/security/pwhistory.conf
      lineinfile:
        path: /etc/security/pwhistory.conf
        regexp: '^remember='
        line: 'remember = 24'
        backup: yes

    - name: Set remember=24 in /etc/pam.d/system-auth
      lineinfile:
        path: /etc/pam.d/system-auth
        regexp: '^\s*password\s+(requisite|required|sufficient)\s+pam_pwhistory\.so'
        line: 'password    requisite    pam_pwhistory.so use_authtok enforce_for_root remember=24'
        backup: yes
      notify: Apply authselect changes

    - name: Set remember=24 in /etc/pam.d/password-auth
      lineinfile:
        path: /etc/pam.d/password-auth
        regexp: '^\s*password\s+(requisite|required|sufficient)\s+pam_pwhistory\.so'
        line: 'password    requisite    pam_pwhistory.so use_authtok enforce_for_root remember=24'
        backup: yes
      notify: Apply authselect changes

    - name: Notify user to manually reboot the system
      debug:
        msg: "Changes applied. Please manually reboot the system for the changes to take effect."

  handlers:
    - name: Apply authselect changes
      command: authselect apply-changes
