---
- name: Ensure password history is configured correctly (CIS 4.4.3.3.1)
  hosts: all
  become: yes
  vars:
    pam_files:
      - system-auth
      - password-auth
    timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}"
  tasks:

    - name: Set remember = 24 in /etc/security/pwhistory.conf
      lineinfile:
        path: /etc/security/pwhistory.conf
        regexp: '^remember\s*='
        line: 'remember = 24'
        create: yes
        backup: yes

    - name: Back up PAM files with timestamp
      copy:
        src: "/etc/pam.d/{{ item }}"
        dest: "/etc/pam.d/{{ item }}.bak_{{ timestamp }}"
        remote_src: yes
      loop: "{{ pam_files }}"

    - name: Remove remember= argument from pam_pwhistory.so lines in authselect custom PAM files
      shell: |
        auth_file="/etc/authselect/$(grep '^custom/' /etc/authselect/authselect.conf | head -n1)/{{ item }}"
        sed -ri 's/(^\s*password\s+(requisite|required|sufficient)\s+pam_pwhistory.so.*)(\s+remember=\s*\S+)(.*$)/\1\4/' "$auth_file"
      loop: "{{ pam_files }}"

    - name: Apply authselect changes
      command: authselect apply-changes

    - name: Notify user to manually reboot the system
      debug:
        msg: "Manual reboot required for password history changes to take full effect."

