- name: Ensure password max sequence is limited to 3
  hosts: all
  become: yes
  vars:
    backup_dir: "/var/backups/pwquality"
    timestamp: "{{ ansible_date_time.iso8601 }}"

  tasks:
    - name: Create backup directory
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'

    - name: Backup existing pwquality.conf with timestamp
      copy:
        src: /etc/security/pwquality.conf
        dest: "{{ backup_dir }}/pwquality.conf-{{ timestamp }}"
        mode: '0644'
      ignore_errors: yes

    - name: Ensure maxsequence is set to 3 in pwquality.conf
      lineinfile:
        path: /etc/security/pwquality.conf
        regexp: '^maxsequence\s*='
        line: 'maxsequence = 3'
        create: yes

    - name: Remove maxsequence override in PAM files
      shell: |
        for l_pam_file in system-auth password-auth; do
          l_authselect_file="/etc/authselect/$(head -1 /etc/authselect/authselect.conf | grep 'custom/')/$l_pam_file"
          sed -ri 's/(^\s*password\s+(requisite|required|sufficient)\s+pam_pwquality.so.*)(\s+maxsequence=\s*[0-9]+)(.*$)/\1\4/' "$l_authselect_file"
        done
        authselect apply-changes

    - name: Notify manual reboot
      debug:
        msg: "Configuration updated. Please reboot the system manually to apply changes."
