---
- name: Secure /var/tmp mount options
  hosts: all
  become: true
  tasks:

    - name: Check if /var/tmp is a separate mount
      command: findmnt -n /var/tmp
      register: var_tmp_mount
      failed_when: false
      changed_when: false

    - name: Ensure /var/tmp has secure mount options in /etc/fstab
      lineinfile:
        path: /etc/fstab
        regexp: '^(\S+\s+/var/tmp\s+\S+\s+)([^#\n]*)'
        line: '\1defaults,rw,nosuid,nodev,noexec,relatime'
        backrefs: yes
      when: var_tmp_mount.rc == 0

    - name: Remount /var/tmp with correct options
      mount:
        path: /var/tmp
        opts: defaults,rw,nosuid,nodev,noexec,relatime
        state: remounted
      when: var_tmp_mount.rc == 0
