---
- name: Ensure sudoers files do not allow NOPASSWD (PRODUCTION SAFE)
  hosts: all
  become: true
  vars:
    sudoers_files:
      - /etc/sudoers.d/100-oracle-cloud-agent-users
      - /etc/sudoers.d/90-cloud-init-users
    backup_dir: "/var/backups/sudoers"
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"

  tasks:

    - name: Ensure backup directory exists
      file:
        path: "{{ backup_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0750'

    - name: Stat sudoers files
      stat:
        path: "{{ item }}"
      loop: "{{ sudoers_files }}"
      register: sudoers_status

    - name: Backup existing sudoers files with timestamp
      copy:
        src: "{{ item.stat.path }}"
        dest: "{{ backup_dir }}/{{ item.stat.path | basename }}.bak.{{ timestamp }}"
        remote_src: true
      loop: "{{ sudoers_status.results }}"
      when: item.stat.exists

    - name: Remove all uncommented NOPASSWD entries from sudoers files
      replace:
        path: "{{ item.stat.path }}"
        regexp: '^[^#\n]*\bNOPASSWD\b[^\n]*\n?'
        replace: ''
      loop: "{{ sudoers_status.results }}"
      when: item.stat.exists

    - name: Validate full sudoers config
      command: "visudo -cf /etc/sudoers"
      register: sudo_check
      changed_when: false
      failed_when: sudo_check.rc != 0

    - name: Validate sudoers.d files individually
      command: "visudo -cf {{ item.stat.path }}"
      loop: "{{ sudoers_status.results }}"
      when: item.stat.exists
      register: sudoersd_check
      changed_when: false
      failed_when: sudoersd_check.results | selectattr('rc', 'ne', 0) | list | length > 0
