---
- name: Ensure sudoers files do not allow NOPASSWD
  hosts: all
  become: true
  vars:
    sudoers_files:
      - /etc/sudoers.d/100-oracle-cloud-agent-users
      - /etc/sudoers.d/90-cloud-init-users
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"

  tasks:

    - name: Check if sudoers file exists
      stat:
        path: "{{ item }}"
      loop: "{{ sudoers_files }}"
      register: sudoers_status

    - name: Backup and clean NOPASSWD lines from sudoers files
      block:
        - name: Backup the sudoers file
          copy:
            src: "{{ item.stat.path }}"
            dest: "{{ item.stat.path }}.bak.{{ timestamp }}"
            remote_src: true

        - name: Remove NOPASSWD entries
          lineinfile:
            path: "{{ item.stat.path }}"
            regexp: '^([^#].*NOPASSWD.*)'
            state: absent
            backrefs: yes
      loop: "{{ sudoers_status.results }}"
      when: item.stat.exists
      loop_control:
        label: "{{ item.stat.path }}"

    - name: Create missing sudoers files with secure content
      copy:
        dest: "{{ item }}"
        content: "# Secure sudoers file created by Ansible\n"
        owner: root
        group: root
        mode: '0440'
      loop: "{{ sudoers_files }}"
      when: item not in sudoers_status.results | selectattr('stat.exists') | map(attribute='stat.path') | list
