---
- name: Remove remember= from pam_unix.so in authselect profile
  hosts: all
  become: yes
  vars:
    pam_files:
      - /etc/authselect/custom/custom_hardened_profile/password-auth
      - /etc/authselect/custom/custom_hardened_profile/system-auth
    timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}"
  tasks:

    - name: Backup PAM files with timestamp
      copy:
        src: "{{ item }}"
        dest: "{{ item }}.bak_{{ timestamp }}"
        remote_src: yes
      loop: "{{ pam_files }}"

    - name: Remove remember= argument from pam_unix.so lines
      lineinfile:
        path: "{{ item }}"
        regexp: '^(?P<start>\s*password\s+(requisite|required|sufficient)\s+pam_unix\.so\s+.*?)(\s+remember=\d+)(?P<end>\s.*|$)'
        line: "\g<start>\g<end>"
        backrefs: yes
      loop: "{{ pam_files }}"

    - name: Apply authselect changes
      command: authselect apply-changes

    - name: Reminder to reboot the system manually
      debug:
        msg: "Manual reboot required to verify changes."
