---
- name: Remove 'remember=' from pam_unix.so in active authselect profile (safe for prod)
  hosts: all
  become: true
  vars:
    timestamp: "{{ lookup('pipe', 'date +%F_%H-%M-%S') }}"
  tasks:

    - name: Get active authselect profile
      command: head -1 /etc/authselect/authselect.conf
      register: authselect_profile_raw
      changed_when: false

    - name: Set authselect profile path
      set_fact:
        pam_profile_path: >-
          {{
            "/etc/authselect/" + authselect_profile_raw.stdout
            if authselect_profile_raw.stdout.startswith("custom/")
            else "/usr/share/authselect/default/" + authselect_profile_raw.stdout
          }}

    - name: Backup password-auth and system-auth with timestamp
      copy:
        src: "{{ item }}"
        dest: "{{ item }}.bak_{{ timestamp }}"
        remote_src: true
      loop:
        - "{{ pam_profile_path }}/password-auth"
        - "{{ pam_profile_path }}/system-auth"

    - name: Remove remember=n from pam_unix.so lines
      replace:
        path: "{{ item }}"
        regexp: '(?<=^\\s*password\\s+(requisite|required|sufficient)\\s+pam_unix\\.so\\s+[^\\n]*)\\s+remember=\\d+'
        replace: ''
      loop:
        - "{{ pam_profile_path }}/password-auth"
        - "{{ pam_profile_path }}/system-auth"

    - name: Apply authselect changes
      command: authselect apply-changes
