---
- name: Remove remember= from pam_unix.so and backup config
  hosts: all
  become: true
  vars:
    timestamp: "{{ lookup('pipe', 'date +%F_%H-%M-%S') }}"
    authselect_conf_path: /etc/authselect/authselect.conf

  tasks:
    - name: Read the current authselect profile
      command: head -1 {{ authselect_conf_path }}
      register: profile_output

    - name: Set pam profile path
      set_fact:
        pam_profile: "{{ profile_output.stdout }}"
        pam_profile_path: >-
          {{ '/etc/authselect/' + profile_output.stdout
             if profile_output.stdout.startswith('custom/')
             else '/usr/share/authselect/default/' + profile_output.stdout }}

    - name: Create backup of password-auth and system-auth with timestamp
      copy:
        src: "{{ item }}"
        dest: "{{ item }}.bak_{{ timestamp }}"
        remote_src: yes
      loop:
        - "{{ pam_profile_path }}/password-auth"
        - "{{ pam_profile_path }}/system-auth"

    - name: Remove remember=n from pam_unix.so lines
      replace:
        path: "{{ item }}"
        regexp: '(^\\s*password\\s+(?:requisite|required|sufficient)\\s+pam_unix\\.so\\s+[^#\\n\\r]*?)\\s*remember=[0-9]+(\\s*.*)?$'
        replace: '\\1\\2'
        backup: no
      loop:
        - "{{ pam_profile_path }}/password-auth"
        - "{{ pam_profile_path }}/system-auth"

    - name: Apply changes via authselect
      command: authselect apply-changes

    - name: Notify manual reboot
      debug:
        msg: "REMINDER: Please manually reboot the system to complete changes."
