---
- name: Ensure pam_unix does not include remember argument
  hosts: all
  become: yes
  tasks:
    
    - name: Backup system-auth and password-auth files
      copy:
        src: "/etc/pam.d/{{ item }}"
        dest: "/etc/pam.d/{{ item }}.bak_{{ ansible_date_time.iso8601 }}"
        backup: yes
      loop:
        - system-auth
        - password-auth

 
    - name: Remove remember=n from pam_unix.so lines
      lineinfile:
        path: "/etc/pam.d/{{ item }}"
        regexp: '^(\s*password\s+(requisite|required|sufficient)\s+pam_unix.so\s+.*)(remember=[1-9][0-9]*)(\s*.*)$'
        line: '\1\3'
        backrefs: yes
      loop:
        - system-auth
        - password-auth

  
    - name: Apply changes with authselect
      command: authselect apply-changes

    
    - name: Verify no remember argument in system-auth
      shell: grep -P '^password\s+sufficient\s+pam_unix.so\s+.*remember=' /etc/pam.d/system-auth
      register: verify_system_auth
      failed_when: verify_system_auth.stdout != ""

    - name: Verify no remember argument in password-auth
      shell: grep -P '^password\s+sufficient\s+pam_unix.so\s+.*remember=' /etc/pam.d/password-auth
      register: verify_password_auth
      failed_when: verify_password_auth.stdout != ""

    - name: Notify success
      debug:
        msg: "Successfully removed remember=n argument from pam_unix.so"
      when: verify_system_auth.stdout == "" and verify_password_auth.stdout == ""
