---
- name: Remove 'remember=' from pam_unix.so with backup
  hosts: all
  become: true
  vars:
    pam_files:
      - /etc/authselect/custom/custom_hardened_profile/password-auth
      - /etc/authselect/custom/custom_hardened_profile/system-auth
    timestamp: "{{ ansible_date_time.iso8601_basic_short }}"

  tasks:
    - name: Backup PAM file with timestamp
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ item }}.bak.{{ timestamp }}"
        remote_src: true
      loop: "{{ pam_files }}"

    - name: Remove remember= from pam_unix.so line
      ansible.builtin.lineinfile:
        path: "{{ item }}"
        regexp: '^(?P<start>\s*password\s+(requisite|required|sufficient)\s+pam_unix\.so\s+.*?)(\s+remember=\d+)(?P<end>\s.*|$)'
        line: '\g<start>\g<end>'
        backrefs: yes
      loop: "{{ pam_files }}"
      register: pam_fix

    - name: Print message for manual reboot
      ansible.builtin.debug:
        msg: "Manual reboot is recommended after this change."
      when: pam_fix is changed
