---
- name: Enforce CIS 4.5.1.2 - Password Expiration ≤ 365 Days
  hosts: all
  become: yes
  vars:
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"
    backup_dir: "/var/backups/ansible_pass_expiry"

  tasks:

    - name: Create backup directory
      file:
        path: "{{ backup_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Backup /etc/login.defs
      copy:
        src: /etc/login.defs
        dest: "{{ backup_dir }}/login.defs.{{ timestamp }}"
        backup: no
        mode: '0644'

    - name: Backup /etc/shadow
      copy:
        src: /etc/shadow
        dest: "{{ backup_dir }}/shadow.{{ timestamp }}"
        backup: no
        mode: '0400'

    - name: Ensure PASS_MAX_DAYS is set to 365 in /etc/login.defs
      lineinfile:
        path: /etc/login.defs
        regexp: '^PASS_MAX_DAYS'
        line: 'PASS_MAX_DAYS 365'
        create: yes
        backup: no

    - name: Get list of users with password hashes and max days > 365
      shell: |
        awk -F: '($2 !~ /^[!*]/ && $5 > 365) {print $1}' /etc/shadow
      register: users_with_high_maxdays
      changed_when: false

    - name: Set max password days to 365 for affected users
      command: chage --maxdays 365 {{ item }}
      loop: "{{ users_with_high_maxdays.stdout_lines }}"
      when: users_with_high_maxdays.stdout_lines | length > 0

    
    
