- name: Ensure password history policy is enforced
  hosts: all
  become: yes
  vars:
    backup_dir: "/var/backups/pwhistory"
    timestamp: "{{ ansible_date_time.iso8601 }}"

  tasks:
    - name: Create backup directory
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'

    - name: Ensure /etc/security/pwhistory.conf exists
      file:
        path: /etc/security/pwhistory.conf
        state: touch
        mode: '0644'

    - name: Backup existing pwhistory.conf with timestamp
      copy:
        src: /etc/security/pwhistory.conf
        dest: "{{ backup_dir }}/pwhistory.conf-{{ timestamp }}"
        mode: '0644'
        remote_src: yes
      ignore_errors: yes

    - name: Ensure password history remembers 24 previous passwords
      lineinfile:
        path: /etc/security/pwhistory.conf
        regexp: '^remember\s*='
        line: 'remember = 24'
        create: yes

    - name: Remove remember override in PAM files
      shell: |
        for l_pam_file in system-auth password-auth; do
          l_authselect_file="/etc/authselect/$(head -1 /etc/authselect/authselect.conf | grep 'custom/')/$l_pam_file"
          sed -ri 's/(^\s*password\s+(requisite|required|sufficient)\s+pam_pwhistory.so.*)(\s+remember=\s*[0-9]+)(.*$)/\1\4/' "$l_authselect_file"
        done
        authselect apply-changes

    - name: Notify manual reboot
      debug:
        msg: "Configuration updated. Please reboot the system manually to apply changes."
