- name: Ensure password history enforcement for root user
  hosts: all
  become: yes
  vars:
    backup_dir: "/var/backups/pwhistory"
    timestamp: "{{ ansible_date_time.iso8601 }}"

  tasks:
    - name: Create backup directory
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'

    - name: Ensure /etc/security/pwhistory.conf exists
      file:
        path: /etc/security/pwhistory.conf
        state: touch
        mode: '0644'

    - name: Backup existing pwhistory.conf with timestamp
      copy:
        src: /etc/security/pwhistory.conf
        dest: "{{ backup_dir }}/pwhistory.conf-{{ timestamp }}"
        mode: '0644'
        remote_src: yes
      ignore_errors: yes

    - name: Ensure enforce_for_root is set in pwhistory.conf
      lineinfile:
        path: /etc/security/pwhistory.conf
        line: 'enforce_for_root'
        create: yes

    - name: Notify manual reboot
      debug:
        msg: "Configuration updated. Please reboot the system manually to apply changes."
