---
- name: Remediate CIS 4.4.3.3.1 - Ensure password history remember is configured
  hosts: all
  become: yes
  vars:
    pwhistory_conf: /etc/security/pwhistory.conf
    pam_files:
      - system-auth
      - password-auth

  tasks:

    - name: Ensure /etc/security/pwhistory.conf exists with correct permissions
      file:
        path: "{{ pwhistory_conf }}"
        state: touch
        mode: '0644'

    - name: Ensure 'remember = 24' is set in /etc/security/pwhistory.conf
      lineinfile:
        path: "{{ pwhistory_conf }}"
        regexp: '^\s*remember\s*='
        line: 'remember = 24'
        create: yes
        mode: '0644'

    - name: Get current authselect profile
      command: authselect current -r
      register: authselect_profile

    - name: Remove 'remember' argument from pam_pwhistory.so in custom profile
      replace:
        path: "/etc/authselect/{{ authselect_profile.stdout }}/{{ item }}"
        regexp: '(?i)(^\s*password\s+(requisite|required|sufficient)\s+pam_pwhistory\.so.*?)\s+remember=\S+'
        replace: '\1'
        backup: yes
      loop: "{{ pam_files }}"
      notify: Apply authselect changes

  handlers:
    - name: Apply authselect changes
      command: authselect apply-changes

  post_tasks:
    - name: Note for Manual Reboot
      debug:
        msg: "Changes applied. Please manually reboot the system to ensure full effect."
