---
- name: Fix Password Expiration Policy
  hosts: all
  become: yes
  vars:
    backup_dir: /root/security_remediations/backups
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"
  
  tasks:
    - name: Create backup directory if it doesn't exist
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0700'
        owner: root
        group: root
      
    - name: Backup /etc/login.defs
      copy:
        src: /etc/login.defs
        dest: "{{ backup_dir }}/login.defs.{{ timestamp }}.bak"
        remote_src: yes
        mode: '0600'
        owner: root
        group: root
      
    - name: Backup /etc/shadow
      copy:
        src: /etc/shadow
        dest: "{{ backup_dir }}/shadow.{{ timestamp }}.bak"
        remote_src: yes
        mode: '0600'
        owner: root
        group: root
        
    - name: Update PASS_MAX_DAYS in /etc/login.defs
      lineinfile:
        path: /etc/login.defs
        regexp: '^PASS_MAX_DAYS'
        line: 'PASS_MAX_DAYS   365'
        backup: no
      register: login_defs_update
        
    - name: Get list of users with passwords
      shell: "awk -F: '$2 != \"*\" && $2 != \"!\" && $2 != \"!!\" {print $1}' /etc/shadow"
      register: password_users
      changed_when: false
      check_mode: no
      
    - name: Update max password age for users with passwords
      command: "chage --maxdays 365 {{ item }}"
      with_items: "{{ password_users.stdout_lines }}"
      register: chage_result
      changed_when: chage_result.rc == 0
