---
- name: Remediate CIS 4.4.3.3.1 - Ensure password history is configured
  hosts: all
  become: yes
  vars:
    pwhistory_conf: /etc/security/pwhistory.conf
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"
    pam_files:
      - system-auth
      - password-auth

  tasks:

    - name: Backup pwhistory.conf if it exists
      copy:
        src: "{{ pwhistory_conf }}"
        dest: "{{ pwhistory_conf }}.{{ timestamp }}"
        remote_src: yes
      when: lookup('ansible.builtin.file', pwhistory_conf, errors='ignore')

    - name: Ensure 'remember = 24' is set in pwhistory.conf
      lineinfile:
        path: "{{ pwhistory_conf }}"
        regexp: '^\s*remember\s*='
        line: 'remember = 24'
        create: yes
        mode: '0644'

    - name: Get custom authselect profile path
      shell: |
        grep 'custom/' /etc/authselect/authselect.conf | cut -d'/' -f2
      register: authselect_profile
      changed_when: false

    - name: Remove 'remember' argument from pam_pwhistory.so in custom profile
      lineinfile:
        path: "/etc/authselect/{{ authselect_profile.stdout }}/{{ item }}"
        regexp: '^(?i)\s*password\s+(requisite|required|sufficient)\s+pam_pwhistory\.so.*\sremember=\S+'
        line: "{{ lookup('file', '/etc/authselect/' ~ authselect_profile.stdout ~ '/' ~ item) | regex_replace('\\sremember=\\S+', '') }}"
        backrefs: no
      loop: "{{ pam_files }}"
      notify: Apply authselect changes

    - name: Reminder - Manual Reboot Required
      debug:
        msg: "✔ Configuration complete. Please reboot the system manually to ensure all PAM and policy changes take effect."

  handlers:
    - name: Apply authselect changes
      command: authselect apply-changes
