---
- name: Ensure password history remember is configured correctly
  hosts: all
  become: true
  tasks:
 
    - name: Get current authselect profile
      command: authselect current
      register: authselect_current
      changed_when: false
 
    - name: Extract current profile name
      set_fact:
        current_profile: "{{ authselect_current.stdout_lines[0].split()[0] }}"
 
    - name: Check if profile is custom
      set_fact:
        custom_profile: "{{ current_profile }}"
        is_custom: "{{ current_profile.startswith('custom/') }}"
 
    - name: Create custom profile if not custom
      when: not is_custom
      block:
        - name: Create a custom profile
          command: >
            authselect create-profile hardening --base-on {{ current_profile }}
          args:
            creates: "/etc/authselect/custom/hardening"
 
        - name: Enable custom profile
          command: >
            authselect select custom/hardening with-sudo with-faillock with-pwhistory --force
 
        - name: Set custom_profile fact
          set_fact:
            custom_profile: "custom/hardening"
 
    - name: Remove remember= from pam_pwhistory.so in system-auth and password-auth
      vars:
        pam_files:
          - system-auth
          - password-auth
      block:
        - name: Patch pam_pwhistory.so lines in {{ item }}
          replace:
            path: "/etc/authselect/{{ custom_profile }}/{{ item }}"
            regexp: '(?i)^(\s*password\s+(requisite|required|sufficient)\s+pam_pwhistory\.so\s+.*)\sremember=\S+'
            replace: '\1'
          loop: "{{ pam_files }}"
 
    - name: Apply Authselect changes
      command: authselect apply-changes
