---
- name: Ensure CUPS is not in use (CIS 2.2.11)
  hosts: all
  become: true
  vars:
    cups_conf_path: /etc/cups/cupsd.conf
    backup_dir: /etc/cups/backups
    timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}"

  tasks:

    - name: Check if cups is installed
      package_facts:
    
    - name: Backup cupsd.conf if exists
      copy:
        src: "{{ cups_conf_path }}"
        dest: "{{ backup_dir }}/cupsd.conf.bak_{{ timestamp }}"
        remote_src: true
      when: "'cups' in ansible_facts.packages"
      ignore_errors: true

    - name: Try to remove cups package
      dnf:
        name: cups
        state: absent
      register: cups_remove_result
      ignore_errors: true

    - name: Mask and stop CUPS services if cups removal failed or is still installed
      block:
        - name: Stop cups.socket and cups.service
          systemd:
            name: "{{ item }}"
            state: stopped
          loop:
            - cups.service
            - cups.socket
          ignore_errors: true

        - name: Mask cups.socket and cups.service
          systemd:
            name: "{{ item }}"
            enabled: false
            masked: true
          loop:
            - cups.service
            - cups.socket
          ignore_errors: true
      when: cups_remove_result is failed or 'cups' in ansible_facts.packages

    - name: Notify user to reboot manually
      debug:
        msg: "Manual reboot required to finalize CUPS service changes. Please reboot the system."

