---
- name: Ensure CUPS is not in use (CIS 2.2.11)
  hosts: all
  become: true
  vars:
    cups_conf_path: /etc/cups/cupsd.conf
    backup_dir: /etc/cups/backups
    timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}"

  tasks:

    - name: Gather installed packages
      package_facts:

    - name: Create backup directory
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'
      when: "'cups' in ansible_facts.packages"

    - name: Backup cupsd.conf if it exists
      copy:
        src: "{{ cups_conf_path }}"
        dest: "{{ backup_dir }}/cupsd.conf.bak_{{ timestamp }}"
        remote_src: true
      when:
        - "'cups' in ansible_facts.packages"
        - ansible_facts.packages.cups is defined
      ignore_errors: true

    - name: Try to remove cups package using yum (fallback for dnf bug)
      yum:
        name: cups
        state: absent
      register: cups_remove_result
      ignore_errors: true

    - name: Mask and stop CUPS services if removal failed or CUPS still exists
      block:
        - name: Stop cups services
          systemd:
            name: "{{ item }}"
            state: stopped
          loop:
            - cups.service
            - cups.socket
          ignore_errors: true

        - name: Mask cups services
          systemd:
            name: "{{ item }}"
            masked: true
          loop:
            - cups.service
            - cups.socket
          ignore_errors: true
      when:
        - cups_remove_result is failed
          # OR cups is still present
        - "'cups' in ansible_facts.packages"

    - name: Notify user to reboot manually
      debug:
        msg: "Manual reboot required to finalize CUPS service changes. Please reboot the system."
