---
- name: Ensure users provide password for privilege escalation
  hosts: all
  become: yes
  tasks:
    - name: Backup sudoers files
      command: cp {{ item }} {{ item }}.bak-$(date +%F-%T)
      loop:
        - /etc/sudoers.d/100-oracle-cloud-agent-users
        - /etc/sudoers.d/90-cloud-init-users

    - name: Remove NOPASSWD entries
      lineinfile:
        path: "{{ item }}"
        state: absent
        regex: '^[^#]*NOPASSWD'
      loop:
        - /etc/sudoers.d/100-oracle-cloud-agent-users
        - /etc/sudoers.d/90-cloud-init-users

    - name: Validate sudo permissions
      command: sudo -l
