---
- name: Ensure users provide password for privilege escalation
  hosts: all
  become: yes
  tasks:
    - name: Create backup directory
      file:
        path: /etc/sudoers_backup
        state: directory
        mode: '0755'

    - name: Check if sudoers files exist
      stat:
        path: "{{ item }}"
      register: sudoers_files
      loop:
        - /etc/sudoers.d/100-oracle-cloud-agent-users
        - /etc/sudoers.d/90-cloud-init-users

    - name: Backup existing sudoers files
      copy:
        src: "{{ item.item }}"
        dest: "/etc/sudoers_backup/{{ item.item | basename }}-backup-{{ ansible_date_time.date }}.{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}{{ ansible_date_time.second }}"
        remote_src: yes
      loop: "{{ sudoers_files.results }}"
      when: item.stat.exists

    - name: Remove NOPASSWD entries if files exist
      lineinfile:
        path: "{{ item.item }}"
        state: absent
        regex: '^[^#]*NOPASSWD'
      loop: "{{ sudoers_files.results }}"
      when: item.stat.exists

    - name: Validate sudo permissions
      command: sudo -l
