---
- name: Ensure sudo commands use PTY
  hosts: all
  become: true
  tasks:

    - name: Ensure use_pty is enforced in sudo
      template:
        src: use_pty.j2
        dest: /etc/sudoers.d/99-use-pty
        owner: root
        group: root
        mode: '0440'
        validate: '/usr/sbin/visudo -cf %s'
