---
- name: Ensure sudo commands use PTY
  hosts: all
  become: true
  tasks:

    - name: Ensure use_pty is enforced in sudo
      copy:
        dest: /etc/sudoers.d/99-use-pty
        content: |
          Defaults use_pty
        owner: root
        group: root
        mode: '0440'
      validate: '/usr/sbin/visudo -cf %s'
