---
- name: Ensure sudo uses PTY
  hosts: all
  become: yes
  tasks:
    - name: Create sudoers file to enforce use_pty
      copy:
        content: "Defaults use_pty\n"
        dest: /etc/sudoers.d/99-use-pty
        owner: root
        group: root
        mode: '0440'
      validate: '/usr/sbin/visudo -cf %s'
