---
- name: Remove GNOME Display Manager
  hosts: all
  become: yes
  tasks:

    - name: Create timestamped backup of relevant files
      command: tar -cvzf /root/gdm_backup_{{ ansible_date_time.epoch }}.tar.gz /etc/gdm/
      args:
        warn: false

    - name: Remove GDM package
      yum:
        name: gdm
        state: absent

   
