---
- name: Ensure rsyslog is configured to send logs to a remote log host
  hosts: all
  become: true
  vars:
    rsyslog_config_path: "/etc/rsyslog.conf"
    rsyslog_d_dir: "/etc/rsyslog.d"
    remote_log_port: 514
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
    forward_rule: |
      *.* action(type="omfwd" target="{{ remote_log_host }}" port="{{ remote_log_port }}" protocol="tcp"
                 action.resumeRetryCount="100"
                 queue.type="LinkedList" queue.size="1000")

  tasks:
    - name: Fail if remote_log_host is not provided
      fail:
        msg: "You must pass the remote_log_host variable using --extra-vars"
      when: remote_log_host is not defined

    - name: Create a backup of rsyslog.conf
      copy:
        src: "{{ rsyslog_config_path }}"
        dest: "{{ rsyslog_config_path }}.{{ timestamp }}.bak"
        remote_src: yes

    - name: Create backups of all rsyslog.d/*.conf files
      shell: |
        for file in {{ rsyslog_d_dir }}/*.conf; do
          [ -f "$file" ] && cp "$file" "$file.{{ timestamp }}.bak";
        done
      args:
        executable: /bin/bash

    - name: Ensure remote forwarding rule is present in /etc/rsyslog.d/99-remote.conf
      copy:
        dest: "{{ rsyslog_d_dir }}/99-remote.conf"
        content: "{{ forward_rule }}\n"
        owner: root
        group: root
        mode: '0644'

    - name: Restart rsyslog to apply changes
      systemd:
        name: rsyslog
        state: restarted
        enabled: true

    - name: Reboot reminder
      debug:
        msg: "Please manually reboot the system to complete verification."
