---
- hosts: all
  become: yes
  vars:
    # Issue banner for remote login
    issue_net_content: |
      WARNING: Authorized users only. All activities may be monitored and reported by Company XYZ.

  tasks:
    - name: "Backup existing /etc/issue.net with timestamp"
      ansible.builtin.shell: |
        if [ -f /etc/issue.net ]; then
          cp /etc/issue.net /etc/issue.net.bak_$(date +"%Y-%m-%d_%H-%M-%S")
        fi
      args:
        warn: false
      tags: [backup, issue_net]

    - name: "Configure /etc/issue.net with site policy banner"
      ansible.builtin.copy:
        content: "{{ issue_net_content }}"
        dest: /etc/issue.net
        owner: root
        group: root
        mode: '0644'
      when: issue_net_content | length > 0
      tags: [configure, issue_net]

    - name: "Remove /etc/issue.net if banner not used"
      ansible.builtin.file:
        path: /etc/issue.net
        state: absent
      when: issue_net_content | length == 0
      tags: [remove, issue_net]

    - name: "Reminder - Manual reboot required to verify changes"
      ansible.builtin.debug:
        msg: "Manual reboot is required after script execution to verify changes."
      tags: [notice]
