---
- name: Ensure rsyslog is configured to send logs to a remote log host
  hosts: all
  become: true
  vars:
    remote_log_host: "{{ remote_log_host_ip }}"  # Passed at runtime or via extra vars

  tasks:
    - name: Backup rsyslog.conf before modification
      copy:
        src: /etc/rsyslog.conf
        dest: "/etc/rsyslog.conf.bak_{{ ansible_date_time.iso8601 }}"

    - name: Ensure rsyslog.d backup directory exists
      file:
        path: "/etc/rsyslog.d_backup_{{ ansible_date_time.iso8601 }}"
        state: directory
        mode: '0755'

    - name: Backup rsyslog.d files before modification (if any)
      shell: |
        if [ -d /etc/rsyslog.d ]; then
          shopt -s nullglob
          files=(/etc/rsyslog.d/*)
          if [ ${#files[@]} -gt 0 ]; then
            cp -r /etc/rsyslog.d/* "/etc/rsyslog.d_backup_{{ ansible_date_time.iso8601 }}/"
          fi
        fi
      args:
        executable: /bin/bash
        warn: false

    - name: Configure rsyslog to send logs to a remote log host
      lineinfile:
        path: /etc/rsyslog.conf
        line: '*.* action(type="omfwd" target="{{ remote_log_host }}" port="514" protocol="tcp" action.resumeRetryCount="100" queue.type="LinkedList" queue.size="1000")'
        state: present
        create: yes
        backup: yes

    - name: Restart rsyslog service
      systemd:
        name: rsyslog
        state: restarted
        enabled: yes
