---
- name: Ensure SELinux is in Enforcing mode
  hosts: all
  become: yes
  tasks:

    - name: Set timestamp variable
      set_fact:
        timestamp: "{{ lookup('pipe', 'date +\"%Y-%m-%d_%H-%M-%S\"') }}"

    - name: Backup /etc/selinux/config file
      command: "cp /etc/selinux/config /backup/selinux_config_backup_{{ timestamp }}"
      when: ansible_facts.os_family == 'RedHat'
      notify:
        - Backup SELinux configuration

    - name: Ensure SELinux is enforcing by setting in /etc/selinux/config
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=enforcing'
        backup: yes
      when: ansible_facts.os_family == 'RedHat'
      notify:
        - SELinux configuration updated

    - name: Ensure SELinux is enforcing by running setenforce
      command: setenforce 1
      when: ansible_facts.os_family == 'RedHat'

    - name: Verify SELinux status
      command: getenforce
      register: selinux_status
      failed_when: selinux_status.stdout != "Enforcing"
      changed_when: false
      when: ansible_facts.os_family == 'RedHat'

    - name: Notify user to manually reboot the system
      debug:
        msg: "SELinux has been set to Enforcing mode. Please reboot the system manually for verification."

  handlers:
    - name: Backup SELinux configuration
      debug:
        msg: "Backup of /etc/selinux/config has been created with timestamp {{ timestamp }}"

    - name: SELinux configuration updated
      debug:
        msg: "The SELINUX parameter in /etc/selinux/config has been updated to 'enforcing'."
