---
- name: Audit SELinux and unconfined services
  hosts: all
  become: true
  tasks:

    - name: Ensure semanage command is available (RHEL-based systems)
      package:
        name: policycoreutils-python-utils
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Ensure semanage command is available (Debian-based systems)
      package:
        name: policycoreutils
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Get SELinux mode (enforcing, permissive, disabled)
      command: getenforce
      register: selinux_mode

    - name: Display current SELinux mode
      debug:
        msg: "SELinux is currently set to: {{ selinux_mode.stdout }}"

    - name: Get list of unconfined services
      shell: |
        ps -eZ | grep unconfined_service_t | awk -F: '{ print $NF }' | sort | uniq
      register: unconfined_services
      changed_when: false

    - name: Display unconfined services
      debug:
        msg: >
          Unconfined services detected:
          {{ unconfined_services.stdout_lines | default(['None found']) }}

    - name: Check if falcon-sensor context exists
      shell: semanage fcontext -l | grep falcon-sensor
      register: falcon_sensor_context
      ignore_errors: true
      changed_when: false

    - name: Show context for falcon-sensor
      debug:
        msg: "{{ falcon_sensor_context.stdout_lines if falcon_sensor_context.stdout_lines else ['No context found for falcon-sensor'] }}"

    - name: Check if falcon-sensor-updater context exists
      shell: semanage fcontext -l | grep falcon-sensor-updater
      register: falcon_updater_context
      ignore_errors: true
      changed_when: false

    - name: Show context for falcon-sensor-updater
      debug:
        msg: "{{ falcon_updater_context.stdout_lines if falcon_updater_context.stdout_lines else ['No context found for falcon-sensor-updater'] }}"

    - name: Check if falcon-agent context exists
      shell: semanage fcontext -l | grep falcon-agent
      register: falcon_agent_context
      ignore_errors: true
      changed_when: false

    - name: Show context for falcon-agent
      debug:
        msg: "{{ falcon_agent_context.stdout_lines if falcon_agent_context.stdout_lines else ['No context found for falcon-agent'] }}"
