---
- name: Ensure SELinux is enabled and targeted policy is set with timestamped backup
  hosts: all
  become: true
  vars:
    selinux_config: /etc/selinux/config
    timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}"
  tasks:

    - name: Backup /etc/selinux/config with timestamp
      copy:
        src: "{{ selinux_config }}"
        dest: "{{ selinux_config }}.bak_{{ timestamp }}"
        remote_src: yes

    - name: Ensure SELINUX=enforcing is set
      replace:
        path: "{{ selinux_config }}"
        regexp: '^SELINUX=.*'
        replace: 'SELINUX=enforcing'

    - name: Ensure SELINUXTYPE=targeted is set
      replace:
        path: "{{ selinux_config }}"
        regexp: '^SELINUXTYPE=.*'
        replace: 'SELINUXTYPE=targeted'

    - name: Print message for manual reboot
      debug:
        msg: |
          SELinux configuration updated. 
          Please reboot the system manually to apply changes.
          Backup created at: {{ selinux_config }}.bak_{{ timestamp }}

    - name: Try to set SELinux enforcing (will fail if SELinux is disabled)
      command: setenforce 1
      ignore_errors: yes
