---
- name: Secure SSH by disabling empty passwords
  hosts: all
  become: yes
  vars:
    sshd_config: /etc/ssh/sshd_config
    timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}"
    backup_file: "{{ sshd_config }}.bak_{{ timestamp }}"

  tasks:
    - name: Back up sshd_config with timestamp
      copy:
        src: "{{ sshd_config }}"
        dest: "{{ backup_file }}"
        remote_src: yes
        mode: '0644'

    - name: Ensure PermitEmptyPasswords is set to no
      lineinfile:
        path: "{{ sshd_config }}"
        regexp: '^[\s#]*PermitEmptyPasswords\s+'
        line: 'PermitEmptyPasswords no'
        state: present
        insertafter: '^#?MaxSessions.*'  # Or adjust to where you'd like it
        backrefs: yes

    - name: Display manual reboot reminder
      debug:
        msg: "✅ sshd_config secured. Please reboot the system manually to complete verification."
