---
- name: Secure SSH MACs in sshd_config
  hosts: all
  become: true

  tasks:
    - name: Block weak MACs at the top of sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        line: >
          MACs -hmac-md5,hmac-md5-96,hmac-ripemd160,hmac-sha1-96,hmac-sha1,
          umac-64@openssh.com,hmac-md5-etm@openssh.com,hmac-md5-96-etm@openssh.com,
          hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,umac-64-etm@openssh.com
        insertafter: BOF
        state: present
        create: yes
        backup: yes

    - name: Add allowed strong MACs
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^MACs\s+(?!-)'
        line: >
          MACs hmac-sha2-512,hmac-sha2-256,umac-128-etm@openssh.com,
          hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com
        state: present
        create: yes
        backup: yes

    - name: Validate sshd configuration
      command: sshd -t
      register: sshd_validate
      changed_when: false
      failed_when: sshd_validate.rc != 0

    - name: Restart sshd if config is valid
      systemd:
        name: sshd
        state: restarted
      when: sshd_validate.rc == 0
