---
- name: Secure SSH KexAlgorithms
  hosts: all
  become: true
  tasks:

    - name: Backup sshd_config with timestamp
      copy:
        src: /etc/ssh/sshd_config
        dest: "/etc/ssh/sshd_config.bak_{{ ansible_date_time.date }}_{{ ansible_date_time.time | regex_replace(':', '-') }}"
        remote_src: true

    - name: Ensure weak KexAlgorithms are disabled
      lineinfile:
        path: /etc/ssh/sshd_config
        insertafter: BOF
        line: "KexAlgorithms -diffie-hellman-group14-sha1"
        state: present
        create: yes
      notify: Restart SSH

    - name: (Optional) Enforce only strong KexAlgorithms (FIPS 140-2 approved)
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^KexAlgorithms '
        line: 'KexAlgorithms ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256'
        insertafter: '^#.*KexAlgorithms'
        state: present
      notify: Restart SSH

  handlers:
    - name: Restart SSH
      service:
        name: sshd
        state: restarted
