- name: Ensure users must provide password for privilege escalation
  hosts: all
  become: yes
  vars:
    timestamp: "{{ ansible_date_time.epoch }}"
    backup_dir: "/var/backups/sudoers"

  tasks:
    - name: Create backup directory if it doesn't exist
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: "0750"

    - name: Find existing sudoers files
      find:
        paths: "/etc/sudoers.d/"
        patterns: "*"
      register: found_sudoers_files

    - name: Backup existing sudoers files with timestamp
      copy:
        src: "{{ item.path }}"
        dest: "{{ backup_dir }}/{{ item.path | basename }}.backup_{{ timestamp }}"
        mode: "0600"
        remote_src: yes
      loop: "{{ found_sudoers_files.files }}"

    - name: Remove NOPASSWD entries from existing sudoers files
      replace:
        path: "{{ item.path }}"
        regexp: '^[^#]*NOPASSWD'
        replace: ''
      loop: "{{ found_sudoers_files.files }}"

    - name: Notify user to reboot the system manually
      debug:
        msg: "Manual reboot required after execution. Please reboot the system to verify changes."
