- name: Ensure users must provide password for escalation
  hosts: all
  become: yes
  vars:
    timestamp: "{{ ansible_date_time.epoch }}"
    backup_dir: "/var/backups/sudoers"
    sudoers_files:
      - "/etc/sudoers.d/100-oracle-cloud-agent-users"
      - "/etc/sudoers.d/90-cloud-init-users"
  tasks:

    - name: Create backup directory if it doesn't exist
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: "0750"

    - name: Backup sudoers files with timestamp
      copy:
        src: "{{ item }}"
        dest: "{{ backup_dir }}/{{ item | basename }}.backup_{{ timestamp }}"
        mode: "0600"
      loop: "{{ sudoers_files }}"
      register: backup_status

    - name: Remove NOPASSWD entries from sudoers files
      replace:
        path: "{{ item }}"
        regexp: '^[^#]*NOPASSWD'
        replace: ''
      loop: "{{ sudoers_files }}"
      register: removal_status

    - name: Notify user to reboot the system manually
      debug:
        msg: "Manual reboot required after execution. Please reboot the system to verify changes."
