---
- name: Ensure sudo privilege escalation requires password
  hosts: all
  become: yes
  vars:
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
    backup_dir: "/var/backups/sudoers"

  tasks:

    - name: Ensure backup directory exists
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'

    - name: Find files in /etc/sudoers.d containing NOPASSWD
      shell: "grep -l '^[^#]*NOPASSWD' /etc/sudoers.d/* || true"
      register: sudoers_with_nopasswd
      changed_when: false

    - name: Set list of matching sudoers files
      set_fact:
        matched_sudoers_files: "{{ sudoers_with_nopasswd.stdout_lines }}"

    - name: Backup matched sudoers files
      copy:
        src: "{{ item }}"
        dest: "{{ backup_dir }}/{{ item | basename }}.{{ timestamp }}"
        remote_src: yes
      loop: "{{ matched_sudoers_files }}"
      when: matched_sudoers_files | length > 0

    - name: Remove NOPASSWD lines from matched files
      lineinfile:
        path: "{{ item }}"
        regexp: '^([^#]*NOPASSWD)'
        state: absent
        backup: no
      loop: "{{ matched_sudoers_files }}"
      when: matched_sudoers_files | length > 0
      notify: manual_reboot

    - name: Add change comment to modified files
      lineinfile:
        path: "{{ item }}"
        line: "# NOPASSWD lines removed by Ansible on {{ ansible_date_time.iso8601 }}"
        insertafter: EOF
      loop: "{{ matched_sudoers_files }}"
      when: matched_sudoers_files | length > 0

  handlers:
    - name: manual_reboot
      debug:
        msg: "NOPASSWD entries removed. Please manually reboot the system to verify changes."
