---
- name: Backup and remove NOPASSWD from sudoers files
  hosts: all
  become: true
  vars:
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
    backup_dir: "/var/backups/sudoers"
  tasks:

    - name: Ensure backup directory exists
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'

    - name: Find sudoers files containing NOPASSWD
      shell: |
        find /etc/sudoers /etc/sudoers.d/ -type f -exec grep -l '^[^#]*NOPASSWD' {} \; 2>/dev/null || true
      register: sudoers_files
      changed_when: false

    - name: Show files with NOPASSWD
      debug:
        var: sudoers_files.stdout_lines

    - name: Backup sudoers files with NOPASSWD
      copy:
        src: "{{ item }}"
        dest: "{{ backup_dir }}/{{ item | basename }}.{{ timestamp }}"
        remote_src: true
      loop: "{{ sudoers_files.stdout_lines }}"
      when: sudoers_files.stdout_lines | length > 0

    - name: Remove NOPASSWD lines from sudoers files
      lineinfile:
        path: "{{ item }}"
        regexp: '^[^#]*NOPASSWD'
        state: absent
      loop: "{{ sudoers_files.stdout_lines }}"
      when: sudoers_files.stdout_lines | length > 0

    - name: Add comment about NOPASSWD removal
      lineinfile:
        path: "{{ item }}"
        line: "# NOPASSWD lines removed by Ansible on {{ ansible_date_time.iso8601 }}"
        insertafter: EOF
      loop: "{{ sudoers_files.stdout_lines }}"
      when: sudoers_files.stdout_lines | length > 0
