---
- name: Ensure sudo log file exists
  hosts: all
  become: yes
  tasks:
    - name: Create timestamped backup of sudoers file
      command: cp /etc/sudoers /etc/sudoers.bak-{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}

    - name: Ensure 'Defaults logfile="/var/log/sudo.log"' exists
      lineinfile:
        path: /etc/sudoers
        line: 'Defaults logfile="/var/log/sudo.log"'
        state: present
        validate: "/usr/sbin/visudo -cf %s"

    - name: Verify sudo configuration
      command: /usr/sbin/visudo -c
      register: sudo_check
      changed_when: sudo_check.rc != 0

    - name: Display verification result
      debug:
        msg: "sudoers file check status: {{ sudo_check.stdout }}"

    - name: Ensure logrotate is set up for sudo logs
      copy:
        dest: /etc/logrotate.d/sudo
        content: |
          /var/log/sudo.log {
              daily
              rotate 7
              compress
              missingok
              notifempty
          }
