---
- name: Remove NOPASSWD from sudoers files and backup
  hosts: all
  become: yes
  vars:
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
    backup_dir: "/var/backups/sudoers"
  tasks:

    - name: Ensure backup directory exists
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'

    - name: Find sudoers files containing NOPASSWD
      shell: "grep -rl '^[^#]*NOPASSWD' /etc/sudoers /etc/sudoers.d/ 2>/dev/null || true"
      register: sudoers_with_nopasswd
      changed_when: false

    - name: Back up each sudoers file with NOPASSWD
      copy:
        src: "{{ item }}"
        dest: "{{ backup_dir }}/{{ item | basename }}.{{ timestamp }}"
        remote_src: yes
      loop: "{{ sudoers_with_nopasswd.stdout_lines }}"
      when: sudoers_with_nopasswd.stdout_lines | length > 0

    - name: Remove NOPASSWD lines from the sudoers files
      lineinfile:
        path: "{{ item }}"
        regexp: '^[^#]*NOPASSWD'
        state: absent
        backup: no
      loop: "{{ sudoers_with_nopasswd.stdout_lines }}"
      when: sudoers_with_nopasswd.stdout_lines | length > 0

    - name: Append audit comment to modified files
      lineinfile:
        path: "{{ item }}"
        line: "# NOPASSWD lines removed by Ansible on {{ ansible_date_time.iso8601 }}"
        insertafter: EOF
      loop: "{{ sudoers_with_nopasswd.stdout_lines }}"
      when: sudoers_with_nopasswd.stdout_lines | length > 0
