---
- name: Setup /var/log mount in AWX
  hosts: all
  become: true
  tasks:
    - name: Ensure /var/log is unmounted
      command: umount /var/log
      ignore_errors: yes  # If /var/log is not mounted, ignore the error
    
    - name: Create /var_log.img file (1GB)
      command: "dd if=/dev/zero of=/var_log.img bs=100M count=10"
      args:
        creates: /var_log.img  # Skip if file already exists
    
    - name: Format /var_log.img as xfs
      command: "mkfs.xfs /var_log.img"
      when: ansible_facts['ansible_mounts'] is not search('/var/log')  # Only format if not formatted already
    
    - name: Mount /var_log.img to /var/log with the correct options
      mount:
        path: /var/log
        src: /var_log.img
        fstype: xfs
        opts: loop,rw,nosuid,nodev,noexec,relatime
        state: mounted
    
    - name: Ensure mount entry is present in /etc/fstab
      lineinfile:
        path: /etc/fstab
        line: '/var_log.img /var/log xfs loop,rw,nosuid,nodev,noexec,relatime 0 0'
        create: yes
