---
- hosts: all
  gather_facts: yes

  tasks:
    - name: Check if /var/log is mounted
      set_fact:
        var_log_mounted: "{{ ansible_mounts | selectattr('mount', 'equalto', '/var/log') | list | length > 0 }}"
    
    - name: Format /var_log.img as xfs
      when: var_log_mounted == false
      command: mkfs.xfs /var_log.img

    - name: Mount /var/log if not mounted
      when: var_log_mounted == false
      mount:
        name: /var/log
        src: /var_log.img
        fstype: xfs
        opts: "loop,rw,nosuid,nodev,noexec,relatime"
        state: mounted
